# Generated by Django 4.0.4 on 2023-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft_living', models.IntegerField()),
                ('sqft_lot', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('yr_built', models.IntegerField()),
                ('view', models.IntegerField()),
            ],
        ),
    ]
